apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: api
      hasuraService: custom
    name: api
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: api
      spec:
        containers:
        - image: hasura/hello-world:latest
          imagePullPolicy: IfNotPresent
          name: api
          env:
          - name: PRODUCTION
            value: "true"
          - name: CLUSTER_NAME 
            value: {{ cluster.name }}
          - name: WIT_ACCESS_TOKEN
            valueFrom:
               secretKeyRef:
                  name: hasura-secrets
                  key: bot.wit_access_token.key  
          - name: NEWS_API_KEY            
            valueFrom:
               secretKeyRef:
                  name: hasura-secrets
                  key: bot.news_api_key.key
          - name: FACEBOOK_VERIFY_TOKEN
              valueFrom:
                secretKeyRef:
                  key: bot.fb_verify_token.key
                  name: hasura-secrets
            - name: FACEBOOK_PAGE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: bot.fb_page_token.key
                  name: hasura-secrets
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
        securityContext: {}
        terminationGracePeriodSeconds: 0
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: api
      hasuraService: custom
    name: api
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: api
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
